{
 "title": "Zond Metrics Exporter (Single)",
 "description": "Companion dashboard for https://github.com/theQRL/zond-metrics-exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(eth_con_beacon_slot, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Execution Client",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version)(eth_exe_web3_client_version{instance=~\"$instance\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Consensus Config",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_spec_config_name{instance=~\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Consensus Fork",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_fork_current{instance=~\"$instance\"}",
     "legendFormat": "{{ fork }}"
    }
   ]
  },
  {
   "title": "Consensus Client",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version)(eth_con_node_version{instance=~\"$instance\"})",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Execution Chain ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_exe_chain_id{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Execution Network ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_exe_network_id{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Consensus Preset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_spec_preset_base{instance=~\"$instance\"}",
     "legendFormat": "{{ preset }}"
    }
   ]
  },
  { "title": "Consensus Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_sync_is_syncing{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Sync Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "eth_con_sync_percentage{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "\n    eth_con_beacon_slot{instance=~\"$instance\", slot!=\"genesis\"}\n",
     "legendFormat": "{{ block_id }}"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "eth_con_beacon_finality_checkpoint_epochs{instance=~\"$instance\", state_id=\"head\", checkpoint!=\"previous_justified\"}",
     "legendFormat": "{{ checkpoint }}"
    }
   ]
  },
  {
   "title": "Epoch distances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Epochs" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n    eth_con_beacon_finality_checkpoint_epochs{instance=~\"$instance\", checkpoint=\"justified\", state_id=\"head\"}\n)\n-\nsum by (instance)(\n    eth_con_beacon_finality_checkpoint_epochs{instance=~\"$instance\", checkpoint=\"finalized\", state_id=\"head\"}\n)",
     "legendFormat": "Justified -> Finalized"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_beacon_finality_checkpoint_epochs{instance=~\"$instance\", checkpoint=\"justified\", state_id=\"head\"}\n)\n-\nsum by (instance)(\n    eth_con_beacon_finality_checkpoint_epochs{instance=~\"$instance\", checkpoint=\"previous_justified\", state_id=\"head\"}\n)",
     "legendFormat": "Justified -> Previous Justified"
    }
   ]
  },
  {
   "title": "Sync Distance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "slots" } },
   "targets": [
    {
     "expr": "eth_con_sync_distance{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sync rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(eth_con_sync_percentage{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Reorgs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum by (instance)(increase(eth_con_beacon_reorg_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Slot distances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Slots" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n    eth_con_beacon_slot{instance=~\"$instance\", block_id=\"head\"}\n)\n-\nsum by (instance) (\n    eth_con_beacon_slot{instance=~\"$instance\", block_id=\"finalized\"}\n) ",
     "legendFormat": "Head -> Finalized"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_beacon_slot{instance=~\"$instance\", block_id=\"head\"}\n)\n-\nsum by (instance) (\n    eth_con_beacon_slot{instance=~\"$instance\", block_id=\"justified\"}\n) != 0",
     "legendFormat": "Head -> Justified"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_beacon_slot{instance=~\"$instance\", block_id=\"justified\"}\n)\n-\nsum by (instance) (\n    eth_con_beacon_slot{instance=~\"$instance\", block_id=\"finalized\"}\n) != 0",
     "legendFormat": "Justified -> Finalized"
    }
   ]
  },
  {
   "title": "Counts Per Block (at head)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "eth_con_beacon_transactions{instance=~\"$instance\", block_id=\"head\"}",
     "legendFormat": "Transactions"
    },
    {
     "expr": "eth_con_beacon_slashings{instance=~\"$instance\", block_id=\"head\", type=\"proposer\"}",
     "legendFormat": "Proposer Slashings"
    },
    {
     "expr": "eth_con_beacon_slashings{instance=~\"$instance\", block_id=\"head\", type=\"attester\"}",
     "legendFormat": "Attester Slashings"
    },
    {
     "expr": "eth_con_beacon_attestations{instance=~\"$instance\",block_id=\"head\"}",
     "legendFormat": "Attestations"
    },
    {
     "expr": "eth_con_beacon_deposits{instance=~\"$instance\",block_id=\"head\"}",
     "legendFormat": "Deposits"
    },
    {
     "expr": "eth_con_beacon_voluntary_exits{instance=~\"$instance\",block_id=\"head\"}",
     "legendFormat": "Voluntary Exits"
    }
   ]
  },
  {
   "title": "Events (per min)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (event)(increase(eth_con_event_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Proposer delay",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg(increase(eth_con_beacon_proposer_delay_bucket{instance=~\"$instance\"}[1m])) by (le)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Withdrawals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(eth_con_beacon_withdrawals_index_max{instance=~\"$instance\", block_id=\"head\"}) by (instance)",
     "legendFormat": "Index Max"
    },
    {
     "expr": "sum(eth_con_beacon_withdrawals_index_min{instance=~\"$instance\", block_id=\"head\"}) by (instance)",
     "legendFormat": "Index Min"
    },
    {
     "expr": "sum(eth_con_beacon_withdrawals{instance=~\"$instance\", block_id=\"head\"}) by (instance)",
     "legendFormat": "Per Block"
    }
   ]
  },
  {
   "title": "Withdrawal Amounts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "gwei" } },
   "targets": [
    {
     "expr": "sum(increase(eth_con_beacon_withdrawals_amount_gwei{instance=~\"$instance\", block_id=\"head\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Peers (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (direction)(eth_con_peers{instance=~\"$instance\", state=\"connected\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fork Epochs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eth_con_fork_epoch{instance=~\"$instance\", fork!=\"SHARDING\"}",
     "legendFormat": "{{ fork }}"
    }
   ]
  },
  { "title": "Execution Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_exe_sync_is_syncing{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Sync Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "eth_exe_sync_percentage{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eth_exe_block_most_recent_number{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eth_exe_net_peer_count{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total Difficulty (trillions)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n    eth_exe_block_head_total_difficulty_trillions{instance=~\"$instance\"}\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sync Distance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "targets": [
    {
     "expr": "eth_exe_sync_highest_block{instance=~\"$instance\"} - eth_exe_sync_current_block{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sync rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(eth_exe_sync_percentage{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Suggested Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "targets": [
    {
     "expr": "eth_exe_gas_price_gwei{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gas Used ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n    eth_exe_block_head_gas_used{instance=~\"$instance\"}\n)\n/\nsum by (instance)( \n    eth_exe_block_head_gas_limit{instance=~\"$instance\"} \n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Transactions per block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (instance)(\n    increase(\n        eth_exe_block_head_transactions_in_block{instance=~\"$instance\"}[1m]\n    )\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "eth_exe_block_head_block_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Transaction Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eth_exe_txpool_transactions{instance=~\"$instance\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Gas used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth_exe_block_head_gas_used{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gas limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth_exe_block_head_gas_limit{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Consensus Spec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consensus Spec",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum by (spec)(\n    label_replace(\n        {__name__=~\"eth_con_spec.*\", instance=~\"$instance\"},\n        \"spec\",\n        \"$1\",\n        \"__name__\",\n        \"eth_con_spec_(.*)\"\n    )\n)",
       "legendFormat": "{{ spec }}"
      }
     ]
    }
   ]
  }
 ]
}