{
 "title": "QRL Metrics Exporter Overview",
 "description": "Companion dashboard for https://github.com/ethpandaops/ethereum-metrics-exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Consensus Spec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Consensus Spec",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "max by (spec)(\n    label_replace(\n        {__name__=~\"qrl_con_spec.*\"},\n        \"spec\",\n        \"$1\",\n        \"__name__\",\n        \"qrl_con_spec_(.*)\"\n    )\n)",
       "legendFormat": "{{ spec }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "(rate(process_cpu_seconds_total[1m]))\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Execution Clients (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (version)(qrl_exe_web3_client_version)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Consensus Clients (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (version)(qrl_con_node_version)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Execution Chain ID",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 10 },
   "targets": [
    { "expr": "qrl_exe_chain_id", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consensus Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(qrl_con_node_version{version=~\".*Qrysm.*\"})",
     "legendFormat": "Qrysm"
    }
   ]
  },
  {
   "title": "Execution Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(qrl_exe_web3_client_version{version=~\".*Gzond.*\"})",
     "legendFormat": "Gzond"
    },
    {
     "expr": "count(qrl_exe_web3_client_version{version=~\".*reth.*\"})",
     "legendFormat": "Reth"
    }
   ]
  },
  {
   "title": "Consensus Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (instance)(qrl_con_sync_is_syncing))"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (instance)(qrl_con_sync_is_syncing{} == 0))",
     "legendFormat": "Synced"
    },
    {
     "expr": "count(count by (instance)(qrl_con_sync_is_syncing{} == 1))",
     "legendFormat": "Out of sync"
    }
   ]
  },
  {
   "title": "Head Slot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "qrl_con_beacon_slot{block_id=\"head\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 18 },
   "targets": [
    {
     "expr": "floor(max by (instance)(qrl_con_beacon_slot{block_id=\"head\"}) / max by (instance)(qrl_con_spec_slots_per_epoch))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Finalized Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 18 },
   "targets": [
    {
     "expr": "qrl_con_beacon_finality_checkpoint_epochs{checkpoint=\"finalized\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Finalized -> Head Slot distance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Slots" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n    qrl_con_beacon_slot{block_id=\"head\"}\n)\n-\nsum by (instance) (\n    qrl_con_beacon_slot{block_id=\"finalized\"}\n) != 0",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(qrl_con_peers)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Fork Epochs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "qrl_con_fork_epoch{fork!=\"GENESIS\"}",
     "legendFormat": "{{instance }} {{ fork }}"
    }
   ]
  },
  {
   "title": "Proposer delay",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 24 },
   "targets": [
    {
     "expr": "avg(increase(qrl_con_beacon_proposer_delay_bucket{}[1m])) by (le)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Attestation Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(increase(qrl_con_event_count{event=\"attestation\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Head Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(increase(qrl_con_event_count{event=\"head\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(increase(qrl_con_event_count{event=\"block\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Contribution&Proof Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(increase(qrl_con_event_count{event=\"contribution_and_proof\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Checkpoint Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(increase(qrl_con_event_count{event=\"finalized_checkpoint\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Vol Exit Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(increase(qrl_con_event_count{event=\"voluntary_exit\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Reorg Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(increase(qrl_con_event_count{event=\"chain_reorg\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Execution Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (instance)(qrl_exe_sync_is_syncing))"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (instance)(qrl_con_sync_is_syncing{} == 0))",
     "legendFormat": "Synced"
    },
    {
     "expr": "count(count by (instance)(qrl_con_sync_is_syncing{} == 1))",
     "legendFormat": "Out of sync"
    }
   ]
  },
  {
   "title": "Sync Distance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "targets": [
    {
     "expr": "sum by (instance)(qrl_exe_sync_highest_block{}) - sum by (instance)(qrl_exe_sync_current_block{})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(qrl_exe_net_peer_count)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "qrl_exe_block_most_recent_number{}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Transactions per block",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by (instance)(\n    increase(\n        qrl_exe_block_head_transactions_in_block[1m]\n    )\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "qrl_exe_block_head_block_size_bytes{}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gas used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "qrl_exe_block_head_gas_used", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Gas Used ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n    qrl_exe_block_head_gas_used\n)\n/\nsum by (instance)( \n    qrl_exe_block_head_gas_limit\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Transaction Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "qrl_exe_txpool_transactions", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Suggested Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Shor" } },
   "targets": [
    { "expr": "qrl_exe_gas_price_shor{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Gas limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "qrl_exe_block_head_gas_limit", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}