{
 "title": "Prysm Latency Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time to call ReceiveBlock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(chain_service_processing_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Time to call postBlockProcess",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "rate(on_block_processing_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "New block head ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(new_block_head_milliseconds_sum[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "New Attestation Head Ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "rate(new_att_head_milliseconds_sum[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Replay to Slot Ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(replay_to_slot_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Replay Blocks Ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "rate(replay_blocks_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Time to call validateStateTransition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(state_transition_processing_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Fork Choice Updated Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(forkchoice_updated_v1_latency_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Get Payload Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(get_payload_v1_latency_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "New Payload Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "rate(new_payload_v1_latency_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Gossip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Block Verification Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(gossip_block_verification_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Agg Attestion Verification Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "rate(gossip_aggregate_attestation_verification_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Block Arrival Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "rate(gossip_block_arrival_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Swarm Handshake Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(libp2p_swarm_handshake_latency_seconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}} early_muxer: {{early_muxer}}"
    }
   ]
  },
  { "title": "I/O Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Boltdb Read Tx Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(bolt_db_read_tx_total[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "BoltDb Write Seconds Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "expr": "rate(bolt_tx_write_seconds_total[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Beacon DB Reading Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(db_beacon_state_reading_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Beacon DB Saving Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "targets": [
    {
     "expr": "rate(db_beacon_state_saving_milliseconds_sum{client_type=\"beacon\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Bolt Pending Pages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "targets": [
    { "expr": "bolt_db_freelist_pending_pages", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Bolt Tx Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 47 },
   "targets": [
    {
     "expr": "rate(bolt_tx_writes_total[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}